import { defineConfig } from 'vitepress';

/*
 * VitePress site config for light-runner.
 *
 * Architecture:
 *   - `docs/index.md` is the bespoke landing (layout: home, raw HTML/CSS preserved)
 *   - `docs/guides/*.md` are user-facing how-to guides
 *   - `docs/api/*.md` is auto-generated by typedoc-plugin-markdown from src/
 *   - GitHub Pages deploys docs/.vitepress/dist/ (configured in .github/workflows/docs.yml)
 *
 * Sidebar for /api/ is intentionally a static list of the public re-exports
 * from src/index.ts. typedoc-plugin-markdown also writes its own README.md /
 * modules.md that we link as the entry point. Adding a new public export ->
 * remember to add it to the sidebar entry below.
 */

const GUIDES = [
  { text: 'Quick start', link: '/guides/quickstart' },
  { text: 'Extract files', link: '/guides/extract' },
  { text: 'Detached runs', link: '/guides/detached' },
  { text: 'Security model', link: '/guides/security' },
  { text: 'gVisor & Kata', link: '/guides/gvisor-kata' },
];

/*
 * API sidebar mirrors the directory tree typedoc-plugin-markdown emits under
 * docs/api/. Adding a new public export -> regenerate the API ref via
 * `npm run docs:typedoc`, then add the corresponding entry here. The list is
 * hand-maintained because VitePress does not auto-generate sidebars from a
 * folder scan.
 */
const API_SIDEBAR = [
  {
    text: 'Overview',
    items: [{ text: 'Public surface', link: '/api/' }],
  },
  {
    text: 'Classes',
    collapsed: false,
    items: [
      { text: 'DockerRunner', link: '/api/classes/DockerRunner' },
      { text: 'Execution', link: '/api/classes/Execution' },
      { text: 'LightRunnerError', link: '/api/classes/LightRunnerError' },
    ],
  },
  {
    text: 'Interfaces',
    collapsed: false,
    items: [
      { text: 'RunRequest', link: '/api/interfaces/RunRequest' },
      { text: 'RunResult', link: '/api/interfaces/RunResult' },
      { text: 'RunnerOptions', link: '/api/interfaces/RunnerOptions' },
      { text: 'ExtractSpec', link: '/api/interfaces/ExtractSpec' },
      { text: 'ExtractResult', link: '/api/interfaces/ExtractResult' },
      { text: 'StopOptions', link: '/api/interfaces/StopOptions' },
      { text: 'RunState', link: '/api/interfaces/RunState' },
    ],
  },
  {
    text: 'Functions',
    collapsed: false,
    items: [
      { text: 'listStates', link: '/api/functions/listStates' },
      { text: 'readState', link: '/api/functions/readState' },
    ],
  },
  {
    text: 'Type aliases',
    collapsed: false,
    items: [
      { text: 'Runtime', link: '/api/type-aliases/Runtime' },
      { text: 'LightRunnerErrorCode', link: '/api/type-aliases/LightRunnerErrorCode' },
    ],
  },
];

export default defineConfig({
  title: 'light-runner',
  description: 'Run untrusted code in hardened Docker containers from Node.js',
  lang: 'en-US',
  cleanUrls: true,
  lastUpdated: true,
  ignoreDeadLinks: 'localhostLinks',

  head: [
    ['link', { rel: 'icon', type: 'image/webp', href: '/banner.webp' }],
    ['meta', { name: 'theme-color', content: '#050608' }],
    ['meta', { property: 'og:title', content: 'light-runner' }],
    [
      'meta',
      {
        property: 'og:description',
        content: 'Run untrusted code in hardened Docker containers from Node.js.',
      },
    ],
    ['meta', { property: 'og:image', content: 'https://enixcode.github.io/light-runner/banner.webp' }],
    ['meta', { property: 'og:url', content: 'https://enixcode.github.io/light-runner/' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['meta', { name: 'twitter:image', content: 'https://enixcode.github.io/light-runner/banner.webp' }],
  ],

  // Bespoke landing + custom theme are dark-only by design (deep ink ground,
  // cyan halo accents, noise + grid background). A light mode would have to
  // be redesigned from scratch, so we lock the appearance to dark and hide
  // the toggle entirely.
  appearance: 'force-dark',

  themeConfig: {
    nav: [
      { text: 'Guides', link: '/guides/quickstart', activeMatch: '^/guides/' },
      { text: 'API', link: '/api/', activeMatch: '^/api/' },
      {
        text: 'v0.10.0',
        items: [
          { text: 'Changelog', link: 'https://github.com/enixCode/light-runner/releases' },
          { text: 'npm', link: 'https://www.npmjs.com/package/light-runner' },
        ],
      },
    ],

    sidebar: {
      '/guides/': [
        { text: 'Guides', items: GUIDES },
      ],
      '/api/': API_SIDEBAR,
    },

    socialLinks: [{ icon: 'github', link: 'https://github.com/enixCode/light-runner' }],

    footer: {
      message: 'Released under the MIT License.',
      copyright: 'light-runner / execution primitive',
    },

    search: {
      provider: 'local',
    },

    editLink: {
      pattern: 'https://github.com/enixCode/light-runner/edit/main/docs/:path',
      text: 'Edit this page on GitHub',
    },

    outline: { level: [2, 3] },
  },
});
